### ISSUE TITLE
Getting error while running queries

### ISSUE THREAD

**Issue by raybittuiq** [turbot/steampipe-plugin-vanta#41]
**Describe the bug**
Getting these error while running the respective queries

`select * from vanta.vanta_computer ;
ERROR:  vanta: graphql: Cannot query field "isPasswordManagerInstalled" on type "macosWorkstationData".
select * from vanta.vanta_integration ;
ERROR:  vanta: graphql: Unknown argument "onlyConnected" on field "Organization.integrations".
select * from vanta.vanta_monitor ;
ERROR:  vanta: graphql: Cannot query field "useRemediationTimelines" on type "TestResult".
select * from vanta.vanta_policy ;
ERROR:  vanta: graphql: Cannot query field "approverName" on type "Policy". Did you mean "approvedAt" or "approver"?
select * from vanta.vanta_user ;
ERROR:  vanta: graphql: Cannot query field "permissionLevel" on type "User".
select * from vanta.vanta_vendor ;
ERROR:  vanta: graphql: Cannot query field "assessmentDocuments" on type "Vendor". Did you mean "assessmentComments"?`

**Steampipe version (`steampipe -v`)**
Example: latest

**Plugin version (`steampipe plugin list`)**
Example: v0.4.0

**To reproduce**
just run the above queries
**Expected behavior**

**Additional context**

**Comment by ParthaI** [comment]
Hello @raybittuiq, apologies for the delayed response. I was able to reproduce the error you're encountering. The root cause is that Vanta has made significant changes to their underlying GraphQL schema, and the query you’re using is now based on an unsupported schema. There are major differences between the previous schema and the [current schema](https://studio.apollographql.com/public/vanta-prod/variant/api-external/schema/reference) provided by Vanta.

We’ll need to update the plugin to align with the new schema, which might introduce breaking changes for some of the tables.

Additionally, Vanta now offers [REST API support](https://developer.vanta.com/reference/createcustomcontrol) along with a [Go SDK](https://github.com/adrianosela/vanta-sdk-go/blob/main/client.go), although it’s currently in beta and has a slightly different authentication mechanism.

We’re conducting some R&D to evaluate both the updated GraphQL queries and the new REST API to stabilize the plugin. Once we finalize the design for the plugin upgrade, we’ll revisit this issue.

Thanks for your patience!
